
version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:3000"
    environment:
      - PUBLIC_API_URL=http://localhost:3000
      - PUBLIC_WEBSOCKET_URL=ws://localhost:3000
    depends_on:
      - backend