# render.yaml (Corrected)
services:
  # Backend Service Configuration
  - type: web
    name: geomesh-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    # NOTE: We will add the DATABASE_URL in the Render UI

  # Frontend Service Configuration
  - type: web
    name: geomesh-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      # This tells the frontend the live URL of the deployed backend
      - key: PUBLIC_API_URL
        value: ${{geomesh-backend.url}}
      # This creates the correct wss:// URL for the live WebSocket
      - key: PUBLIC_WEBSOCKET_URL
        value: wss://${{geomesh-backend.url.replace('https://', '')}}