# render.yaml
services:
  # Backend Service Configuration
  - type: web
    name: geomesh-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      # The DATABASE_URL will be added securely in the Render dashboard
      - key: DATABASE_URL
        fromDatabase:
          name: geomesh-db-neon # Placeholder name for our DB
          property: connectionString

  # Frontend Service Configuration
  - type: web
    name: geomesh-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      # These special values automatically use the live URL of your deployed backend
      - key: PUBLIC_API_URL
        value: ${{geomesh-backend.url}}
      - key: PUBLIC_WEBSOCKET_URL
        value: wss://${{geomesh-backend.url}}

databases:
  # This tells Render to connect to our existing Neon database
  - name: geomesh-db-neon
    # This will be added in the Render dashboard
    connectionString: ${{ secrets.NEON_DB_URL }} # Placeholder for the Neon DB connection string